### ISSUE TITLE
When receiving a parsed message through a broadcast intent, the string extra in the intent with key "message_type" does not match "ussd" or "sms" as described in the docs

### ISSUE THREAD

**Issue by stcastle** [UseHover/SDK-Issues#13]
The values with the key "message_type" seem to actually be status values. For example, I have seen "pending" as the value from `intent.getStringExtra("message_type")`

**Comment by davkutalek** [comment]
@stcastle I'm unable to reproduce this. Does it happen with a specific action? In which versions of the SDK have you seen it?

**Comment by stcastle** [comment]
I've seen I know in the latest version `0.17.0-SNAPSHOT02`, and probably in the first snapshot also. I know that it was occurring frequenitly in the Hover Test mode, and is also happening in normal mode. I logged it as a non-fatal exception [here](https://console.firebase.google.com/u/0/project/nala-interface/crashlytics/app/android:money.nala.pay/issues/5c5d9359f8b88c29631e1066). Flipping through those logs I only see it for check balance on Voda, Airtel, and Tigo, but I only flipped through a sample of those logs (by going to the "Logs" tab then filtering on "Events" and looking at the event properties for the last transaction finish event).

**Comment by stcastle** [comment]
@davkutalek I think I royally messed this one up. I think all the errors I was getting were because I was trying to parse "message_type" from the intent returned after a USSD result. It works in the intent received from the broadcast receiver after a matched parser. In my mind I thought it would be "ussd" on the intent from a USSD session and "sms" from a parser, but that doesn't make sense. I recommend closing the issue.
