### ISSUE TITLE
When an SMS confirmation message is split into 2 due to character length, the parser will match correctly, but I receive 2 broadcast intents with status = "succeeded"

### ISSUE THREAD

**Issue by stcastle** [UseHover/SDK-Issues#14]
The two separate broadcast intents with status "succeeded" will have separate values for "response_message" in the intent. The preferred behavior is to have a single broadcast intent for the matched parser, with the response_message containing the full concatenated string from the SMS.

Example, the SMS was split into two as follows:

first SMS and first response_message from broadcast intent
> 6B942189W8Y Confirmed. On 9/2/19 at 9:48 AM Withdraw Tsh1,000.00 from XXXXXX - XXXXX General Supplies HO Till and charged Tsh350.00. New M-Pesa balance i

second SMS and second response_message from broadcast intent
> s Tsh43,092.00

The other metadata, including uuid, with the intent is the same for both intents received by the broadcast receiver.

EDIT: agent till number and name replaced with X for privacy. length of the message is preserved.

**Comment by davkutalek** [comment]
@stcastle I believe this is fixed. Correct behavior as of now is to get one SMS miss for the first half before getting one success broadcast with the full message of both SMS together.
