### ISSUE TITLE
When I update my named groups for my parsers in the Hover dashboard, the keys for the transaction_extras do not update

### ISSUE THREAD

**Issue by stcastle** [UseHover/SDK-Issues#17]
We use "agentCode" as an input variable, and formerly used this for a named group in a parser for transaction_extras. We wanted to change the named group in the parser to "recipientNumber" but it is not updating.

**Comment by davkutalek** [comment]
p0 bug found in parsing in 0.17.0-rc11. It will be fixed in the next release.
