### ISSUE TITLE
Some devices do not detect SIM(s) correctly

### ISSUE THREAD

**Issue by davkutalek** [UseHover/SDK-Issues#19]
msg from benji: 

>User has a tigo sim card in their phone, updated nala, tried to make a payment, then this popped up. >They’ve not changed sim cards.

>(We’ve had a few complaints about this on our customer care portal).

Will get list of affected devices

**Comment by davkutalek** [comment]
![image from ios](https://user-images.githubusercontent.com/735966/53044239-4e22d380-343f-11e9-8527-0fcb3411913e.jpg)

**Comment by davkutalek** [comment]
TECNO Camon CX API 24

**Comment by stcastle** [comment]
We have had 2 more complaints about this same issue, specifically asking for a TIGO SIM.

TECNO TECNO CA6
OS Level 24

...trying to find the other one

**Comment by stcastle** [comment]
@davkutalek I'm having trouble locating all the requests from users. Here is the SIM info from an error with Halotel SIM, though I could not find the device ID.

imsi=6409
mobileCountryCode=640
mobileNetworkCode=09
countryIso=
iccId=89255090029271511093
operatorNameFromHover=HALOTEL
osReportedHni=6409
latestSlotIndex=1
latestSubscriptionId=6

**Comment by davkutalek** [comment]
We believe this issue is solved as of version 1.2.0.

**Comment by Ab3id** [comment]
Device model

H5312/Infinix X572

the device with two sim cards inserted the Vodacom sim card is on sim 2, but when the app tries to start session the no Vodacom sim card error appears, but when the vodacom sim card is on the first slot it works perfectly

**Comment by davkutalek** [comment]
@Ab3id thanks we will get that device. What version of the SDK are you using?

**Comment by Ab3id** [comment]
@davkutalek 
1.4.0

**Comment by jshorland** [comment]
@davkutalek added a chore to pivotal. Can I assign to you?

**Comment by davkutalek** [comment]
yep

**Comment by davkutalek** [comment]
This has been tested on the Infinix X572 and seems to work. Closing this issue in favor of opening individual issues for each device going forward.
