### ISSUE TITLE
Changing SIM cards does not behave correctly

### ISSUE THREAD

**Issue by davkutalek** [UseHover/SDK-Issues#21]
On Fero Mega_LTE dual SIM, Android 6.0, SDK 0.17.0-rc12:

When a single SIM is inserted in slot 1 works fine. Device is turned off and the SIM is changed to a different SIM from the same network. When the action is run it presents 2 SIM choices, SIM 0  and SIM 1. Choosing "SIM 1" works, choosing SIM 0 seems to cause "SIM 1" to appear on confirm screen.

![image](https://user-images.githubusercontent.com/735966/54764434-05347b00-4bb5-11e9-951a-41a7649e7bcf.png)

**Comment by davkutalek** [comment]
Reproduced: In Q-mobile, inserted 2 different SIMs, both are detected and work correctly. Removing either (or both) causes it to report that SIM as being in slot 0

**Comment by davkutalek** [comment]
Patched in 0.17.0-rc13

**Comment by raybesiga** [comment]
Great work @davkutalek!
