### ISSUE TITLE
Unknown host 'maven.usehover.com'

### ISSUE THREAD

**Issue by Stashare** [UseHover/SDK-Issues#23]
using Mac, getting this error: ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.hover:android-sdk:1.0.2.

**Comment by davkutalek** [comment]
We were just updating our maven server to https. It should be working now, please try it again and let us know if it works for you.

**Comment by Stashare** [comment]
Great! 👍, It is working now

**Comment by Stashare** [comment]
Hey @davkutalek, getting "failed to resolve: com.hover:android-sdk:1.0.2" again today.

**Comment by davkutalek** [comment]
Not able to reproduce. Can you confirm that you are online and Android Studio is not set to offline mode?

**Comment by Stashare** [comment]
Working now, I had missed to add a maven line in one of my gradle.properties files. Thanks though
