### ISSUE TITLE
Translates the menu as response for wrong password in 1.2.1

### ISSUE THREAD

**Issue by mijiga** [UseHover/SDK-Issues#24]
in the new version, for some USSD where the PIN is asked before anything, the api considers the menu after that as response saying the entered pin is incorrect.
My Log data show the last USSD dialog displayed a menu: 
D/Hover Response: Select Service
    1 Account Transactions 
    2 Send Money 
    3 Make Payment 
    4 Top up  
    5 Cash/Agent Service 
    6 PIN Change 
    7 Exit
     contains the message from the operator

But in a case where the provider asks to select language first then pin second it works just fine.

**Comment by davkutalek** [comment]
Looks like it is detecting the option "PIN Change" as a request to re-enter the PIN, which it should not. Let me look into that and see if we can push a fix

**Comment by mijiga** [comment]
> Looks like it is detecting the option "PIN Change" as a request to re-enter the PIN, which it should not. Let me look into that and see if we can push a fix

oh okay that makes sense. Will wait on that.

**Comment by davkutalek** [comment]
Just pushed a fix for that: SDK version `1.2.2`. Let me know if that works and if you run into anymore issues like that. We may need to add support for multiple languages somehow.

**Comment by mijiga** [comment]
> Just pushed a fix for that: SDK version `1.2.2`. Let me know if that works and if you run into anymore issues like that. We may need to add support for multiple languages somehow.

Yeah it works thanks.
