### ISSUE TITLE
When I restart my device with an  example app using Hover the accessibility pop-up appears.

### ISSUE THREAD

**Issue by kevahere** [UseHover/SDK-Issues#30]
After building a simple app to test the Hover SDK with one action the app runs as expected. Whenever I restart the device, the Accessibility permission pop-up appears on the screen. The test device is a Samsung Galaxy J4+ Dual SIM. The app used Hover SDK version 1.4.5-androidx

**Comment by davkutalek** [comment]
This is beyond our control. When accessibility turns off without a device restart it can be due to memory usage. We can reduce memory usage by the SDK, but we can't control dev's apps. For restarts there is just nothing we can do, this is just how Android accessibility works (on some devices)
