### ISSUE TITLE
parsed_variables not being returned by broadcastReceiver

### ISSUE THREAD

**Issue by jshorland** [UseHover/SDK-Issues#31]
installed SDK in Application, created an action and set up a parser. till now everything works well but when i wanted to get  the data from it in the broadcastReceiver, i didn't find the "parsed_variables" in the intent.hasExtra("parsed_variables"). Everything showing in dashboard though.

**Comment by jshorland** [comment]
@ishuah can you try to reproduce this tomorrow? If confirmed bug, please fix ASAP. This is a p0 if it's there.

**Comment by ishuah** [comment]
@jshorland  Which version of the SDK did you install?

**Comment by houssemAllaoua** [comment]
@ishuah  1.5.0 and 1.5.1 the same problem in both versions

**Comment by houssemAllaoua** [comment]
@ishuah  I hade a doubt that maybe I'm doing it wrong  so there is my code

**Comment by houssemAllaoua** [comment]
public class GetPhoneNumber extends AppCompatActivity {


    private TransactionReceiver mReceiver = new TransactionReceiver();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ask_for_permission);

      
        ImageButton getNumberBtn =  findViewById(R.id.getNumberBtn);
        getNumberBtn.setEnabled(true);
        getNumberBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent i = new HoverParameters.Builder( GetPhoneNumber.this)
                        .request("fc90f556") .buildIntent();
                startActivityForResult(i, 0);
                mReceiver.onReceive(AskForPermission.this,i);
            }

}

**Comment by houssemAllaoua** [comment]
public class TransactionReceiver extends BroadcastReceiver {

    String TAG = "Receiver";

    public TransactionReceiver() {
    }

    @Override
    public void onReceive(Context context, final Intent intent) {
        String uuid = intent.getStringExtra("uuid");

        Bundle bundle = intent.getExtras();
        if (bundle != null) {
            for (String key : bundle.keySet()) {
                Log.e(TAG, key + " : " + (bundle.get(key) != null ? bundle.get(key) : "NULL"));
            }
        }


    }
}

**Comment by houssemAllaoua** [comment]
and that is what I got 
@ishuah 

2020-03-19 14:43:51.960 9859-9859/com.Houssem.Foxy E/Receiver: show_desc : false
2020-03-19 14:43:51.960 9859-9859/com.Houssem.Foxy E/Receiver: extras : {}
2020-03-19 14:43:51.960 9859-9859/com.Houssem.Foxy E/Receiver: private_extras : {}
2020-03-19 14:43:51.961 9859-9859/com.Houssem.Foxy E/Receiver: dev_style : 2131624139
2020-03-19 14:43:51.961 9859-9859/com.Houssem.Foxy E/Receiver: env : 0
2020-03-19 14:43:51.961 9859-9859/com.Houssem.Foxy E/Receiver: processing_msg : NULL
2020-03-19 14:43:51.961 9859-9859/com.Houssem.Foxy E/Receiver: action_id : fc90f556
2020-03-19 14:43:51.961 9859-9859/com.Houssem.Foxy E/Receiver: timeout_ms : 10000
2020-03-19 14:43:51.961 9859-9859/com.Houssem.Foxy E/Receiver: final_msg_length : 5000
2020-03-19 14:43:51.961 9859-9859/com.Houssem.Foxy E/Receiver: header_msg : NULL

**Comment by androidmaven** [comment]
Hi @houssemAllaoua. There's something you're missing, and we'll get it right together. 

Firstly, kindly screenshot your manifest file where you referenced Receivers (without your keys)

**Comment by houssemAllaoua** [comment]
![z](https://user-images.githubusercontent.com/61784389/77172500-5922ba00-6abe-11ea-995e-d12afd1dd1f1.png)

**Comment by androidmaven** [comment]
@houssemAllaoua Thank you for you fast response. Kindly try these things.

1. Change from action android:name="com.Houssen.Foxy.Hover.CONFIRMED_TRANSACTION"

to -  action android:name="com.Houssen.Foxy.CONFIRMED_TRANSACTION"

Then try again, and let's know if it solves the problem.

Also, please don't forget to regenerate your API key for security purposes, as they are visible in your screenshot. 

Thanks.

**Comment by houssemAllaoua** [comment]
no that didn't work

**Comment by androidmaven** [comment]
Apologies, I had a typo in your package name:

com.Houssem.Foxy.CONFIRMED_TRANSACTION. Please try this instead.

**Comment by houssemAllaoua** [comment]
I did it right  the first time

**Comment by androidmaven** [comment]
Alright, let's dive a bit further.

In your TransactionReceiver. Let's log and verify some information by copy and replacing this in your receiver.

private String TAG_TEST = "HOVER_RECEIVE";
	public TransactionReceiver() { }

	@Override
	public void onReceive(Context context, Intent intent) {
		String uuid = intent.getStringExtra("uuid");

		Log.d(TAG_TEST,"UUID WITH: "+uuid);
		
		if (intent.hasExtra("parsed_variables")) {
			Log.d(TAG_TEST,"YES_PARSED_VARIABLES");
			
		}
		else {
			Log.d(TAG_TEST,"PARSED_VARIABLES_NOT_FOUND");
		}
	}


Kindly confirm if you can log your UUID. If it doesen't, refractor back your action:name and try again.

**Comment by houssemAllaoua** [comment]
with or without refactoring the log was

2020-03-20 14:32:21.483 3968-3968/com.Houssem.Foxy D/Receiver: UUID WITH: null
2020-03-20 14:32:21.483 3968-3968/com.Houssem.Foxy D/Receiver: PARSED_VARIABLES_NOT_FOUND

**Comment by androidmaven** [comment]
Alright, thanks. We're getting closer .

I can see this in your code: 

private TransactionReceiver mReceiver = new TransactionReceiver();

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_ask_for_permission);

  
    ImageButton getNumberBtn =  findViewById(R.id.getNumberBtn);
    getNumberBtn.setEnabled(true);
    getNumberBtn.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            Intent i = new HoverParameters.Builder( GetPhoneNumber.this)
                    .request("fc90f556") .buildIntent();
            startActivityForResult(i, 0);
            mReceiver.onReceive(AskForPermission.this,i);
        }


///// Remove 
"private TransactionReceiver mReceiver = new TransactionReceiver();"
and 
"  mReceiver.onReceive(AskForPermission.this,I);" 

from the file.

How does that go?

**Comment by houssemAllaoua** [comment]
the action is running fine the problem is in the parsing if I do not call the broadcast receiver how will I be able to parse the variables ??

**Comment by androidmaven** [comment]
You do not need to call the broadcast receiver. We do that for you automatically.

**Comment by ishuah** [comment]
@houssemAllaoua do you have time for a call today?

**Comment by houssemAllaoua** [comment]
I just need access to the parsed variable to store it in SQLite and  pass it to my backend

**Comment by houssemAllaoua** [comment]
@ishuah yes you can call me any time

**Comment by androidmaven** [comment]
Happy issues resolved.

**Comment by houssemAllaoua** [comment]
thank you, Tobi, for being so helpful and understanding the support call was great, without your help I would not solve it in million years

**Comment by Yankande** [comment]
Bonjour j'ain un probleme avec l'integration du sdk avec react pouvez vous nous aider ?
