### ISSUE TITLE
AndroidX issues

### ISSUE THREAD

**Issue by ray86** [UseHover/SDK-Issues#34]
I added the project depedency to the gradle file and the app failed to compile.
It works with Appcompact but fails on androidX.
I used the following for androidx
implementation 'com.hover:android-sdk:1.5.2-androidx'
and added the following to the build.gradle
 mavenCentral()
 maven { url "http://maven.usehover.com/releases" }

The error below occurs
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.hover:android-sdk:1.5.2-androidx

**Comment by davkutalek** [comment]
Thanks, will update

**Comment by parapara01** [comment]
je vous salus tous, j'essai d'implementer hover sdk dans mon application sans succes. jai fais des tests qui ont marche correctement mais le probleme c'est que je n'arrivais pas a reccupere les informations retour content dans le message dans mon broadcastreceiver. alors j'aimerais avoir des piste et tuto.merci d'avance

**Comment by parapara01** [comment]
en plus jai fais tellement des test que mon compte hover est bloque.
