### ISSUE TITLE
Error code 1003

### ISSUE THREAD

**Issue by NehlTech** [UseHover/SDK-Issues#35]
I always get 'Could not validate your API Key, see your web dashboard for details' whilst the Api matches with the one on my dashboard. I also get Error code 2005: Missing parameter. You must specify. please can you help me out since i am beginner. Thank you

**Comment by davkutalek** [comment]
To prevent "Could not validate your API Key" your applicationId in your app/build.gradle must also match what you entered for the app in the Hover dashboard.

Error code 2005 is is when you have specified a variable step in the action, but haven't provided a variable value in the code.
