### ISSUE TITLE
Bypass Confirmation screen

### ISSUE THREAD

**Issue by riyadhzen** [UseHover/SDK-Issues#41]
Hello.
We are using an action of type "Variable USSD Longstring". The variables are added through variable steps with no issues.
We use this for airtime top up linked to our external servers. Ideally we want the operation to execute automatically as soon as the app receives info from our servers (This is an internal app that is not shared to the public).
Sadly, the first thing that we are faced with when the ussd operation starts is this screen
![Screenshot_20200522_111941_com arsily](https://user-images.githubusercontent.com/15954752/82660135-b6073180-9c21-11ea-976c-bde077d896ce.jpg)

Is there a way to bypass this screen (move away from it) automatically without clicking on continue?
Thanks

**Comment by ishuah** [comment]
Hi @riyadhzen.
Unfortunately there's no way around this, the SDK has to display the confirmation screen.
