### ISSUE TITLE
Final USSD dialog message showing on top of Splash Screen 

### ISSUE THREAD

**Issue by bensonokiora** [UseHover/SDK-Issues#54]
A final dialog message pops up for milliseconds before the service terminates it. Is there a way to hide it since it's disrupting the UI

![Screenshot_20210302-181933](https://user-images.githubusercontent.com/12033587/109673373-033c0a80-7b87-11eb-8c78-94e31dd8b1bc.jpg)

https://user-images.githubusercontent.com/12033587/109673443-17800780-7b87-11eb-9c9a-9a9c1cdf044e.mp4

That's the final response. The splash-dialog is dismissed immediately after. But the final response is shown on top of the splash-dialog before being dismissed

**Comment by davkutalek** [comment]
@bensonokiora probably a device specific issue, what device is this?

**Comment by bensonokiora** [comment]
One plus 7 Pro

**Comment by bensonokiora** [comment]
I have been testing some devices which are common in Africa and each one has different output.

 For instance, **Samsung**  & **Infinix**  devices are working well with the Splash Activity, but devices like **One Plus** (Android 11), **Huawei** must have the final USSD response dialog "overlayShowing permissions" which overrides the one for Hover. 

Some devices like **Oppo** don't work at all. Always saying to input SIM. 

Some like **Techno Devices** on every session request have "overlayShowing permissions" override on every multi-step UssD request. (They can't run on the background)
