### ISSUE TITLE
error 7002 in the end of the transaction

### ISSUE THREAD

**Issue by AngelusNerdz** [UseHover/SDK-Issues#56]
When I start using the SDK yerstday it was function fine but today I start receive this error and ins't in doc

**Comment by mijiga** [comment]
Share the logs/stacktrace

**Comment by AngelusNerdz** [comment]
Give me some minutes!

**Comment by AngelusNerdz** [comment]
04-05 23:26:10.960 20320-20320/com.example.ussdprocessor I/TransactionSequence: Initiating request: 5fcffa87 Testando
04-05 23:26:11.020 20320-20320/com.example.ussdprocessor W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
04-05 23:26:11.100 20320-20320/com.example.ussdprocessor D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
04-05 23:26:11.120 20320-20320/com.example.ussdprocessor W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
04-05 23:26:11.150 20320-20320/com.example.ussdprocessor D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
04-05 23:26:11.190 20320-20320/com.example.ussdprocessor I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@a8cf64c time:31261789
04-05 23:26:11.200 20320-20320/com.example.ussdprocessor V/ActivityThread: updateVisibility : ActivityRecord{be96bd token=android.os.BinderProxy@a26c9de {com.example.ussdprocessor/com.example.ussdprocessor.MainActivity}} show : false
04-05 23:26:11.720 20320-20320/com.example.ussdprocessor I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@a8cf64c time:31262311
04-05 23:26:12.680 20320-20320/com.example.ussdprocessor I/HoverAccessService: Received response from operator, carrying out action.
04-05 23:26:12.850 20320-20320/com.example.ussdprocessor V/ActivityThread: updateVisibility : ActivityRecord{c40d562 token=android.os.BinderProxy@a8cf64c {com.example.ussdprocessor/com.hover.sdk.api.SessionActivity}} show : true
04-05 23:26:13.840 20320-20320/com.example.ussdprocessor D/ViewRootImpl: #3 mView = null
04-05 23:26:16.060 20320-20320/com.example.ussdprocessor I/ClipboardDataText: text write to parcel
04-05 23:26:16.350 20320-20348/com.example.ussdprocessor I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=71afd5b2-5876-4264-886d-4de3eea37393, tags={ com.hover.sdk.sims.MultiSimTelephonyWorker } ]
04-05 23:26:17.880 20320-20320/com.example.ussdprocessor I/ClipboardDataText: text write to parcel
04-05 23:26:19.480 20320-20320/com.example.ussdprocessor I/ClipboardDataText: text write to parcel
04-05 23:26:21.750 20320-20320/com.example.ussdprocessor I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@a8cf64c time:31272341
04-05 23:26:22.590 20320-20320/com.example.ussdprocessor I/HoverAccessService: Received response from operator, carrying out action.
04-05 23:26:29.330 20320-20320/com.example.ussdprocessor V/ActivityThread: updateVisibility : ActivityRecord{c40d562 token=android.os.BinderProxy@a8cf64c {com.example.ussdprocessor/com.hover.sdk.api.SessionActivity}} show : true
04-05 23:26:34.280 20320-20320/com.example.ussdprocessor I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@a8cf64c time:31284874
04-05 23:26:49.110 20320-20320/com.example.ussdprocessor D/ViewRootImpl: ViewPostImeInputStage processPointer 0
04-05 23:26:49.180 20320-20320/com.example.ussdprocessor D/ViewRootImpl: ViewPostImeInputStage processPointer 1
04-05 23:26:57.620 20320-20320/com.example.ussdprocessor I/TimerSingleton: ERROR 5001: %1$s timeout reached, please check your network connection and your action configurations.
04-05 23:26:57.640 20320-20320/com.example.ussdprocessor E/HoverRequest: setting request error: ERROR CODE 7001: Network error, please try again.
04-05 23:26:57.640 20320-20320/com.example.ussdprocessor I/TransactionSequence: Finished carrying out action, cleaning up.
04-05 23:26:57.680 20320-20320/com.example.ussdprocessor I/Timeline: Timeline: Activity_launch_request id:com.example.ussdprocessor time:31308278
04-05 23:26:57.780 20320-20320/com.example.ussdprocessor I/ClipboardDataText: text write to parcel
04-05 23:26:57.800 20320-20320/com.example.ussdprocessor E/AccessibilityExecutor: Fatal failure: ERROR CODE 7001: Network error, please try again.
04-05 23:26:57.830 20320-20320/com.example.ussdprocessor E/AccessibilityExecutor: Fatal failure: ERROR CODE 7001: Network error, please try again.
04-05 23:26:57.850 20320-20320/com.example.ussdprocessor E/HoverActivity: Failure: null
04-05 23:26:57.900 20320-20320/com.example.ussdprocessor I/TransactionSequence: Finished carrying out action, cleaning up.
04-05 23:26:57.910 20320-20320/com.example.ussdprocessor E/HoverRequest: setting request error: Transaction id not set
04-05 23:26:58.040 20320-20320/com.example.ussdprocessor I/Timeline: Timeline: Activity_launch_request id:com.example.ussdprocessor time:31308631
04-05 23:26:58.040 20320-22729/com.example.ussdprocessor I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-05 23:26:58.040 20320-22729/com.example.ussdprocessor I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-05 23:26:58.070 20320-20320/com.example.ussdprocessor I/TransactionSequence: Finished carrying out action, cleaning up.
04-05 23:26:58.070 20320-20320/com.example.ussdprocessor E/HoverRequest: setting request error: Transaction id not set
04-05 23:26:58.150 20320-20320/com.example.ussdprocessor I/Timeline: Timeline: Activity_launch_request id:com.example.ussdprocessor time:31308744
04-05 23:26:58.150 20320-22730/com.example.ussdprocessor I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-05 23:26:58.150 20320-22730/com.example.ussdprocessor I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-05 23:26:58.300 20320-20320/com.example.ussdprocessor W/ResourcesManager: getTopLevelResources: /data/app/com.example.ussdprocessor-1/base.apk / 1.0 running in com.example.ussdprocessor rsrc of package null
04-05 23:26:58.320 20320-20320/com.example.ussdprocessor W/ResourcesManager: getTopLevelResources: /data/app/com.example.ussdprocessor-1/base.apk / 1.0 running in com.example.ussdprocessor rsrc of package null
04-05 23:26:58.330 20320-20320/com.example.ussdprocessor W/ResourcesManager: getTopLevelResources: /data/app/com.example.ussdprocessor-1/base.apk / 1.0 running in com.example.ussdprocessor rsrc of package null
04-05 23:26:58.340 20320-20320/com.example.ussdprocessor E/HoverActivity: Failure: null
04-05 23:26:58.460 20320-20320/com.example.ussdprocessor D/TextView: setTypeface with style : 0
04-05 23:26:58.570 20320-20320/com.example.ussdprocessor D/ViewRootImpl: #1 mView = android.widget.LinearLayout{b17529 V.E...... ......I. 0,0-0,0}
04-05 23:26:58.570 20320-20348/com.example.ussdprocessor E/WM-WorkerWrapper: Didn't find WorkSpec for id db3a9f1d-0871-414b-8b83-7591f55c7ba3
04-05 23:26:58.660 20320-20336/com.example.ussdprocessor I/art: Background partial concurrent mark sweep GC freed 105108(6MB) AllocSpace objects, 22(740KB) LOS objects, 45% free, 19MB/35MB, paused 5.883ms total 351.207ms
04-05 23:26:58.690 20320-20320/com.example.ussdprocessor D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
04-05 23:26:58.690 20320-20349/com.example.ussdprocessor I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=b97b8693-a69f-4cf6-b829-b0b1cc5becfa, tags={ com.hover.sdk.sms.MessageLogWorker } ]
04-05 23:26:58.700 20320-20349/com.example.ussdprocessor I/WM-WorkerWrapper: Setting status to enqueued for 4902db70-1d96-45f4-ae9e-a353dbc966ec
04-05 23:26:58.700 20320-20320/com.example.ussdprocessor W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
04-05 23:26:58.760 20320-20320/com.example.ussdprocessor I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@a26c9de time:31309353
04-05 23:26:58.780 20320-20320/com.example.ussdprocessor D/ViewRootImpl: #3 mView = null
04-05 23:26:58.860 20320-20435/com.example.ussdprocessor I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-05 23:26:58.860 20320-20435/com.example.ussdprocessor I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-05 23:26:58.860 20320-20435/com.example.ussdprocessor I/qtaguid: Tagging socket 42 with tag 9c9c231f00000000{2627478303,0} uid -1, pid: 20320, getuid(): 10283
04-05 23:26:58.860 20320-20435/com.example.ussdprocessor I/qtaguid: Untagging socket 42
04-05 23:26:59.030 20320-20435/com.example.ussdprocessor I/qtaguid: Tagging socket 42 with tag 9c9c231f00000000{2627478303,0} uid -1, pid: 20320, getuid(): 10283
04-05 23:26:59.710 20320-20435/com.example.ussdprocessor I/qtaguid: Tagging socket 51 with tag 9c9c231f00000000{2627478303,0} uid -1, pid: 20320, getuid(): 10283
04-05 23:26:59.990 20320-20435/com.example.ussdprocessor I/qtaguid: Untagging socket 42
04-05 23:27:00.000 20320-20348/com.example.ussdprocessor I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=4902db70-1d96-45f4-ae9e-a353dbc966ec, tags={ com.hover.sdk.transactions.TransactionUpWorker } ]
04-05 23:27:02.000 20320-20320/com.example.ussdprocessor D/ViewRootImpl: #3 mView = null
04-05 23:27:17.610 20320-20320/com.example.ussdprocessor V/ActivityThread: updateVisibility : ActivityRecord{be96bd token=android.os.BinderProxy@a26c9de {com.example.ussdprocessor/com.example.ussdprocessor.MainActivity}} show : true
![image](https://user-images.githubusercontent.com/48868193/113634521-cb812080-9666-11eb-95f5-0e9d9ff95931.png)
![image](https://user-images.githubusercontent.com/48868193/113634619-f2d7ed80-9666-11eb-9590-b1a5a044cc58.png)

**Comment by davkutalek** [comment]
Looks like it is unable to reach the network or the network USSD is down

**Comment by AngelusNerdz** [comment]
Thanks to all but I already wrote my own code using using accessibility service to manage USSD sessions, thanks
