### ISSUE TITLE
https://maven.usehover.com/realeases

### ISSUE THREAD

**Issue by kennedymakokha** [UseHover/SDK-Issues#60]
https://maven.usehover.com/realeases  url does not have anything so my app fails _with Could not get resource 'http://maven.usehover.com/releases/com/hover/android-sdk/1.7.2/android-sdk-1.7.2.pom'_

**Comment by davkutalek** [comment]
You should be using http not https. Also you've spelled releases wrong: http://maven.usehover.com/releases

**Comment by kennedymakokha** [comment]
it is redirecting to https
