### ISSUE TITLE
Is there a way for Hover to choose menu options when the choice corresponding to each number changes

### ISSUE THREAD

**Issue by davkutalek** [UseHover/SDK-Issues#9]
For example: Random order for bundles in a menu, or a list of account number choices which are not known ahead of time.

**Comment by aliumujib** [comment]
@davkutalek I guess this issue informed the `select number by text variable` feature in the SDK. I noticed a bug however, for example in Nigeria bank menus are sometimes paged.

1. GTBank
2. Access Bank
3. USBC Bank
4. More Options ...

I have a use case where I want to match a bank option in the next page (4). Using a regex, if the option isn't found on the first page. the SDK does nothing and the request times out. How do I go about fixing this?

**Comment by androidmaven** [comment]
Hi @aliumujib , based on your use-case. You need to know the list banks name. What you can do is to have two actions for example (*737*8*Accessbank#) and (*737*8*Next*Wemabank#).

Just incase you know for sure which page (wema bank for example) will be, you just need to use the second option. But in a case where you do not know which page: You can first call action 1, if it fails, then automatically call action 2 in your action Result.

**Comment by davkutalek** [comment]
Closing since selecting numbered choices by text is supported as of SDK version 1.5.1. Opening a new issue for supporting next page automatically.
